/**
 * Email verification code DTO.
 * Mirrors the backend EmailCodeDto contract.
 */
export interface EmailCodeDto {
  id: number;

  /**
   * Recipient email address.
   */
  email: string;

  /**
   * Verification code generated by the server.
   */
  code: string;

  /**
   * Code creation date.
   * Generated automatically by the backend.
   */
  dateEnvoi?: string | null;

  /**
   * Code expiration date.
   * Automatically set by the backend (15 minutes).
   */
  dateExpiration?: string | null;

  /**
   * Associated user identifier.
   */
  userId: number;
}

/**
 * Request used to generate a verification code.
 */
export interface GenerateEmailCodeRequest {
  email: string;
}

/**
 * Request used to verify a verification code.
 */
export interface VerifyEmailCodeRequest {
  email: string;
  code: string;
}